# -*- coding: utf-8 -*-
"""Introdução a machine Learning .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGPEdfsWOtkilUgUGYQowuSfrTzuWtFE
"""

#pelo longo?
#perna curta?
#faz auau?

porco1=[0,1,0]
porco2=[0,1,1]
porco3=[1,1,0]

cachorro1= [0, 0, 1]
cachorro2= [1,0,1]
cachorro3=[1,1,1]

#nada ver com os de cima

treino_x=[porco1, porco2, porco3, cachorro1, cachorro2, cachorro3];
treino_y=[1,1,1,0,0,0]

from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=100,
          multi_class='ovr', penalty='12', random_state=None, tol=0.0001, verbose=0)
animal_misterioso=[1,1,1]
model.predict([animal_misterioso])

array([0])

    misterio1=[1,1,1]
    misterio2=[1,1,0]
    misterio3=[0,1,1]

    teste_x= [misterio1, misterio2, misterio3]
    teste_y= [0,1,1]

    previsoes= modelo.predic(teste_x)
    previsoes

#pelo longo?
#perna curta?
#faz auau?

porco1=[0,1,0]
porco2=[0,1,1]
porco3=[1,1,0]

cachorro1= [0, 0, 1]
cachorro2= [1,0,1]
cachorro3=[1,1,1]

#nada ver com os de cima

treino_x=[porco1, porco2, porco3, cachorro1, cachorro2, cachorro3];
treino_y=[1,1,1,0,0,0]

from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=100,
          multi_class='ovr', penalty='12', random_state=None, tol=0.0001, verbose=0)
animal_misterioso=[1,1,1]
modelo.predict([animal_misterioso])

array([0])

misterio1=[1,1,1]
misterio2=[1,1,0]
misterio3=[0,1,1]

teste_x= [misterio1, misterio2, misterio3]
teste_y= [0,1,1]

previsoes= modelo.predict(teste_x)
previsoes

#pelo longo?
#perna curta?
#faz auau?

porco1=[0,1,0]
porco2=[0,1,1]
porco3=[1,1,0]

cachorro1= [0, 0, 1]
cachorro2= [1,0,1]
cachorro3=[1,1,1]

#nada ver com os de cima

treino_x=[porco1, porco2, porco3, cachorro1, cachorro2, cachorro3];
treino_y=[1,1,1,0,0,0]

from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=100,
          multi_class='ovr', penalty='12', random_state=None, tol=0.0001, verbose=0)
animal_misterioso=[1,1,1]
modelo.predict([animal_misterioso])

array([0])

misterio1=[1,1,1]
misterio2=[1,1,0]
misterio3=[0,1,1]

teste_x= [misterio1, misterio2, misterio3]
teste_y= [0,1,1]

previsoes= modelo.predict(teste_x)
previsoes

import numpy as np

#pelo longo?
#perna curta?
#faz auau?

porco1=[0,1,0]
porco2=[0,1,1]
porco3=[1,1,0]

cachorro1= [0, 0, 1]
cachorro2= [1,0,1]
cachorro3=[1,1,1]

#nada ver com os de cima

treino_x=[porco1, porco2, porco3, cachorro1, cachorro2, cachorro3];
treino_y=[1,1,1,0,0,0]

from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=100,
          multi_class='ovr', penalty='12', random_state=None, tol=0.0001, verbose=0)
animal_misterioso=[1,1,1]
modelo.predict([animal_misterioso])

list(np.array([0]))

misterio1=[1,1,1]
misterio2=[1,1,0]
misterio3=[0,1,1]

teste_x= [misterio1, misterio2, misterio3]
teste_y= [0,1,1]

previsoes= modelo.predict(teste_x)
previsoes

import numpy as np

#pelo longo?
#perna curta?
#faz auau?

porco1=[0,1,0]
porco2=[0,1,1]
porco3=[1,1,0]

cachorro1= [0, 1, 1]
cachorro2= [1,0,1]
cachorro3=[1,1,1]

#nada ver com os de cima

treino_x=[porco1, porco2, porco3, cachorro1, cachorro2, cachorro3];
treino_y=[1,1,1,0,0,0]

from sklearn.svm import LinearSVC

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=100,
          multi_class='ovr', penalty='12', random_state=None, tol=0.0001, verbose=0)
animal_misterioso=[1,1,1]
modelo.predict([animal_misterioso])

list(np.array([0]))

misterio1=[1,1,1]
misterio2=[1,1,0]
misterio3=[0,1,1]

teste_x= [misterio1, misterio2, misterio3]
teste_y= [0,1,1]

previsoes= modelo.predict(teste_x)
previsoes

from sklearn.metrics import accuracy_score

accuracy_score(teste_y, previsoes)

import pandas as pd

url = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
dados = pd.read_csv(url)
dados.head()

x = dados[["home", "how_it_works", "contact"]]
x.head( )

y = dados ["bought"]
y.head( )

from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split

modelo = LinearSVC()
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y)
modelo.fit(treino_x, treino_y)



previsoes = modelo.predict(teste_x)
accuracy_score(teste_y, previsoes)*100

treino_x.shape

teste_x.shape



